# Generated by Django 4.2.27 on 2026-03-07 21:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("external_id", models.UUIDField(unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("currency", models.CharField(max_length=3)),
                ("billing_address", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
